In [2]:
import numpy as np

In [3]:
a = np.array([1,2,3,4])

In [4]:
print(a)

[1 2 3 4]


In [5]:
print(a[1])

2


In [6]:
a[1] = 7

In [7]:
print(a)

[1 7 3 4]


In [8]:
print(a.type())

AttributeError: 'numpy.ndarray' object has no attribute 'type'

In [9]:
print(type(a))

<class 'numpy.ndarray'>


In [10]:
print(a.dimn)

AttributeError: 'numpy.ndarray' object has no attribute 'dimn'

In [11]:
print(a.ndim)

1


In [12]:
b = np.array([1,2,3],[4,5,6],[7,8,9])

TypeError: array() takes from 1 to 2 positional arguments but 3 were given

In [13]:
b = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [14]:
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [15]:
b.ndim

2

In [17]:
b = np.array([[[1,2,3],[4,5,6],[7,8,9]]])

In [18]:
b.ndim

3

In [19]:
b = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [20]:
b[1][0]

np.int64(4)

In [21]:
b[1][0] = 12

In [22]:
b

array([[ 1,  2,  3],
       [12,  5,  6],
       [ 7,  8,  9]])

In [23]:
k = np.array([1,2,3,4,5], ndmin = 5)

In [24]:
k

array([[[[[1, 2, 3, 4, 5]]]]])

In [25]:
k = np.array([1,2,3,4,5], ndmin = 2)

In [26]:
k

array([[1, 2, 3, 4, 5]])

In [27]:
k[0]

array([1, 2, 3, 4, 5])

In [28]:
k[1]

IndexError: index 1 is out of bounds for axis 0 with size 1

In [29]:
k[0][3]

np.int64(4)

In [30]:
k[0][2] = 7

In [31]:
k

array([[1, 2, 7, 4, 5]])

In [32]:
k = np.array([1,2,3,4,5], ndmin = 3)

In [33]:
k

array([[[1, 2, 3, 4, 5]]])

In [34]:
k[0]

array([[1, 2, 3, 4, 5]])

k[0][0][2]

In [35]:
k[0][0][2]

np.int64(3)

In [1]:
import numpy as np

In [2]:
a=[1,2,3],[4,5,6],[7,8,9]

In [ ]:
np

In [1]:
import numpy as np

In [2]:
a=np.array([1,2,3,4,5])

In [8]:
b=np.where(a<0  ,  1,0)

In [9]:
b

array([0, 0, 0, 0, 0])